In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('gurgaon_properties.csv')

In [4]:
df.shape

(3974, 20)

In [5]:
df.duplicated().sum()

13

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3974 entries, 0 to 3973
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3974 non-null   object
 1   society          3973 non-null   object
 2   price            3954 non-null   float64
 3   price_per_sqft   3954 non-null   float64
 4   area             3954 non-null   float64
 5   areaWithType     3974 non-null   object
 6   bedRoom          3974 non-null   int64
 7   bathroom         3974 non-null   int64
 8   balcony          3974 non-null   object
 9   additionalRoom   3974 non-null   object
 10  address          3963 non-null   object
 11  floorNum         3952 non-null   float64
 12  facing           2796 non-null   object
 13  agePossession    3973 non-null   object
 14  nearbyLocations  3767 non-null   object
 15  description      3974 non-null   object
 16  furnishDetails   2940 non-null   object
 17  features         3264 non-null   object
 18  rating           3524 non-null   object
 19  property_type    977 non-null    object
dtypes: float64(4), int64(2), object(14)
memory usage: 621.1+ KB

In [7]:
df.isnull().sum()

property_name         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             22
facing             1178
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1034
features            710
rating              450
property_type      2997
dtype: int64

In [8]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [9]:
df.head()

,property_name,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type
0,4 BHK Flat in Mehrauli Gurgaon Road,essel towers,2.75,Mehrauli Road,12500.0,2200.0,Built Up area: 2200 (204.39 sq.m.),4,5,3+,"study room,servant room","Mehrauli Gurgaon Road, Mehrauli Gurgaon Road, ...",8.0,East,10+ Year Old,"['Mg road metro station', 'Iffco chowk metro s...","Recently renovated, tastefully done 4 bed room...","['1 Water Purifier', '9 Fan', '1 Exhaust Fan',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5...",NaN
1,2 BHK Flat in Sector 95A Gurgaon,signature signum 95a,0.40,Sector 95A,7782.0,514.0,Carpet area: 514 (47.75 sq.m.),2,2,2,not available,"Sector 95A Gurgaon, Gurgaon, Haryana",3.0,East,0 to 1 Year Old,NaN,Prime location\r\nAll necessary shops are in p...,"['3 Fan', '1 Geyser', '5 Light', '1 Chimney', ...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment5 out of 5', 'Safety5 out of 5', ...",NaN
2,3 BHK Flat in Sector 37D Gurgaon,bptp terra,1.71,Sector 37D,7804.0,2191.0,Built Up area: 2191 (203.55 sq.m.),3,3,3+,study room,"7th Floor, Sector 37D Gurgaon, Gurgaon, Haryana",7.0,South-West,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",This beautiful 3 bhk flat in sector 37d gurgao...,"['6 Fan', '5 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Swimming Pool', 'Park', 'Internet...","['Green Area4.5 out of 5', 'Construction4.5 ou...",NaN
3,3 BHK Flat in Sector 37D Gurgaon,bptp terra,1.72,Sector 37D,7850.0,2191.0,Super Built up area 2191(203.55 sq.m.),3,3,3+,servant room,"9th Floor, Sector 37D Gurgaon, Gurgaon, Haryana",10.0,South-East,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",Check out this 3 bhk apartment for sale in bpt...,"['5 Fan', '5 Light', '3 AC', 'No Bed', 'No Chi...","['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...","['Green Area4.5 out of 5', 'Construction4.5 ou...",NaN
4,3 BHK Flat in Sector 63 Gurgaon,dhoot time residency,3.00,Sector 63,18271.0,1642.0,Built Up area: 1642 (152.55 sq.m.)Carpet area:...,3,3,3+,servant room,"Sector 63, Sector 63 Gurgaon, Gurgaon, Haryana",14.0,NaN,1 to 5 Year Old,"['Metro Station', 'High end group housing', 'N...",Best in class property available at sector 63 ...,"['3 Wardrobe', '8 Fan', '1 Exhaust Fan', '3 Ge...",NaN,"['Green Area4 out of 5', 'Construction4 out of...",NaN

In [10]:
df['sector'] = df['sector'].str.lower()

In [11]:
df.head()

,property_name,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type
0,4 BHK Flat in Mehrauli Gurgaon Road,essel towers,2.75,mehrauli road,12500.0,2200.0,Built Up area: 2200 (204.39 sq.m.),4,5,3+,"study room,servant room","Mehrauli Gurgaon Road, Mehrauli Gurgaon Road, ...",8.0,East,10+ Year Old,"['Mg road metro station', 'Iffco chowk metro s...","Recently renovated, tastefully done 4 bed room...","['1 Water Purifier', '9 Fan', '1 Exhaust Fan',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5...",NaN
1,2 BHK Flat in Sector 95A Gurgaon,signature signum 95a,0.40,sector 95a,7782.0,514.0,Carpet area: 514 (47.75 sq.m.),2,2,2,not available,"Sector 95A Gurgaon, Gurgaon, Haryana",3.0,East,0 to 1 Year Old,NaN,Prime location\r\nAll necessary shops are in p...,"['3 Fan', '1 Geyser', '5 Light', '1 Chimney', ...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment5 out of 5', 'Safety5 out of 5', ...",NaN
2,3 BHK Flat in Sector 37D Gurgaon,bptp terra,1.71,sector 37d,7804.0,2191.0,Built Up area: 2191 (203.55 sq.m.),3,3,3+,study room,"7th Floor, Sector 37D Gurgaon, Gurgaon, Haryana",7.0,South-West,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",This beautiful 3 bhk flat in sector 37d gurgao...,"['6 Fan', '5 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Swimming Pool', 'Park', 'Internet...","['Green Area4.5 out of 5', 'Construction4.5 ou...",NaN
3,3 BHK Flat in Sector 37D Gurgaon,bptp terra,1.72,sector 37d,7850.0,2191.0,Super Built up area 2191(203.55 sq.m.),3,3,3+,servant room,"9th Floor, Sector 37D Gurgaon, Gurgaon, Haryana",10.0,South-East,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",Check out this 3 bhk apartment for sale in bpt...,"['5 Fan', '5 Light', '3 AC', 'No Bed', 'No Chi...","['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...","['Green Area4.5 out of 5', 'Construction4.5 ou...",NaN
4,3 BHK Flat in Sector 63 Gurgaon,dhoot time residency,3.00,sector 63,18271.0,1642.0,Built Up area: 1642 (152.55 sq.m.)Carpet area:...,3,3,3+,servant room,"Sector 63, Sector 63 Gurgaon, Gurgaon, Haryana",14.0,NaN,1 to 5 Year Old,"['Metro Station', 'High end group housing', 'N...",Best in class property available at sector 63 ...,"['3 Wardrobe', '8 Fan', '1 Exhaust Fan', '3 Ge...",NaN,"['Green Area4 out of 5', 'Construction4 out of...",NaN

In [12]:
df['sector'].value_counts()

sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 90                                                     90
sector 65                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     68
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 48                                                     58
sector 95                                                     57
sector 56                                                     57
sector 89                                                     56
sector 70a                                                    55
nirvana country                                               53
sector 70                                                     53
sector 37c                                                    53
palam vihar                                                   52
sector 84                                                     51
sector-33 sohna                                               51
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 1                                                   44
dlf phase 2                                                   43
sector 113                                                    43
sector 61                                                     42
sector 82                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 54                                                     27
sector 71                                                     27
laxman vihar                                                  27
dlf phase 4                                                   26
sector 112                                                    25
sector 33                                                     23
sector 88a                                                    23
sector 111                                                    22
dlf phase 3                                                   22
sector 67a                                                    22
sector 82a                                                    20
sector 22                                                     20
sector 78                                                     19
sector 91                                                     18
sector 63a                                                    18
sector 74                                                     18
sector 62                                                     17
sector 99                                                     16
sushant lok phase 3                                           16
sector 110                                                    16
sector 60                                                     15
sector 63                                                     15
sector 14                                                     15
gwal pahari                                                   14
sector 52                                                     14
rajendra park                                                 14
sector 1 imt manesar                                          14
sector 76                                                     14
sector 3                                                      14
dlf phase 5                                                   14
sector 53                                                     14
sector 46                                                     13
sector 36a                                                    13
uppals southend                                               13
laxman vihar phase 2                                          13
sohna road                                                    12
sector 50                                                     12
sector 31                                                     12
sector 38                                                     12
sector 39                                                     12
sector 93                                                     12
sector 9a                                                     11
ashok vihar phase 3 extension                                 11
sector 47                                                     11
sector 7                                                      10
sector 1a imt manesar                                         10
sector 55                                                     10
sector 4                                                       9
c block sushant lok phase 1                                    9
south city 1                                                   9
ashok vihar phase 2                                            9
sector 95a                                                     9
malibu town                                                    8
sector 10a                                                     8
dwarka expressway                                              8
sector 59                                                      8
mehrauli  road                                                 8
sector 40                                                      8
sector 89 a                                                    8
sector 43                                                      8
sector 57                                                      8
palam vihar extension                                          8
sector 58                                                      7
new colony                                                     7
sector 51                                                      7
sector 11                                                      7
sector 36 sohna                                                7
mianwali colony                                                7
sector 26                                                      7
surat nagar 1                                                  7
rajiv nagar                                                    6
ashok vihar                                                    6
sector 5                                                       6
jyoti park                                                     6
sector 1                                                       6
greenwood city                                                 6
jacobpura                                                      6
sector 28                                                      5
sector 2                                                       5
ansal plaza                                                    5
sector 30                                                      5
sushant lok phase 2                                            5
sector 23a                                                     5
arjun nagar                                                    5
manesar                                                        5
sector 9                                                       5
sector 80                                                      5
subhash nagar                                                  5
dayanand colony                                                5
sector 105                                                     5
saraswati vihar                                                5
chakkarpur                                                     5
new palam vihar                                                5
shivaji nagar                                                  4
valley view estate                                             4
imt manesar                                                    4
bhondsi                                                        4
ravi nagar                                                     4
sector 12                                                      4
dharam colony                                                  4
madanpuri                                                      4
sector 36                                                      4
vishnu garden                                                  4
sector 3a                                                      4
sector 6                                                       4
suncity                                                        4
bhim nagar                                                     4
sector 45                                                      4
new                                                            4
krishna colony                                                 4
sector 12a                                                     4
sector 17                                                      4
adarsh nagar                                                   4
baldev nagar                                                   4
garhi harsaru                                                  4
shivpuri                                                       4
devilal colony                                                 4
surya vihar                                                    4
b block sushant lok phase 1                                    3
patel nagar                                                    3
sector 110 a                                                   3
sector 23                                                      3
sector 8                                                       3
laxmi garden                                                   3
gandhi nagar                                                   3
sector 27                                                      3
sector 15                                                      3
sector 88b                                                     3
sector 17b                                                     3
sector 17a                                                     3
shakti nagar                                                   3
maruti kunj                                                    3
mg road                                                        3
sector 73                                                      3
a block sushant lok phase 1                                    3
prem nagar                                                     3
rajiv chowk                                                    2
sector 21                                                      2
daulatabad                                                     2
west rajiv nagar                                               2
nars                                                           2
new basti                                                      2
hira nagar                                                     2
sector 15 part 2                                               2
samaspur                                                       2
golf course road                                               2
faridabad road                                                 2
surat nagar                                                    2
new palam vihar phase 1                                        2
sispal vihar                                                   2
pratap nagar                                                   2
shanti nagar                                                   2
new palam vihar phase 2                                        2
surat nagar phase 2                                            2
sector-2 sohna                                                 2
sohna  road                                                    2
farukhnagar                                                    2
shankar vihar                                                  2
bhawani enclave                                                2
sushant lok                                                    2
lajpat nagar                                                   2
rosewood                                                       2
acharya puri                                                   2
sheetla colony                                                 2
sector 24                                                      2
sector 32                                                      2
manohar nagar                                                  2
mohan nagar                                                    2
bissar                                                         2
ambience island                                                2
sector 41                                                      2
, delhi ncr                                                    2
sector 15 part 1                                               2
sector-11 sohna                                                2
block a surya vihar                                            2
iffco chowk                                                    2
golf course ext road                                           2
mayfield garden                                                2
damdma                                                         1
ram nagar                                                      1
sector 9b                                                      1
new jyoti park                                                 1
kheri                                                          1
carterpuri village                                             1
pataudi road                                                   1
sector 17c                                                     1
mahavir pura                                                   1
sector-35 sohna                                                1
sector 21a faridabad                                           1
rajiv colony                                                   1
ravi nager basai road                                          1
sultanpur                                                      1
huda saraswati vihar                                           1
vir nagar                                                      1
sector 42                                                      1
tekchand nagar                                                 1
sector 37b                                                     1
kanahi                                                         1
block h ashok vihar phase iii extension                        1
sector 5 chowk                                                 1
sector-7 hous                                                  1
sector 4 urban estate                                          1
laxman vihar, railway road,                                    1
nirvana country pocket h                                       1
bhora kalan                                                    1
laxmna vihar, phase 2                                          1
cyber city                                                     1
park view                                                      1
jacobpura near sadar bazar                                     1
anand garden, sector-105                                       1
near sector 1 market                                           1
godrej aria , sector 79 ,                                      1
civil l                                                        1
saraswati enclave                                              1
near euro                                                      1
south city                                                     1
mahalaxmi garden, rajendra place                               1
sector 13                                                      1
new colony, sector 7                                           1
block g sector-57                                              1
ansal's palam vihar                                            1
begampur khatola                                               1
urban estate, sector 5                                         1
udyog vihar phase 1                                            1
sai kunj                                                       1
near nand hospital                                             1
alipur                                                         1
old delhi road, opp sector-14                                  1
sec 3 bhim vihar part 1 bhimgher kheri                         1
gopal nagar, garhi ghasita, sonipat                            1
near pataudi chowk                                             1
dhankot                                                        1
b1 block sector 57                                             1
devi lal colony gali no 12 gurgaon nr omkar public school      1
ashok vihar phase 3                                            1
ats marigold                                                   1
shivji park colony                                             1
sadar bazar                                                    1
ashok vihar phase i                                            1
sector 37a                                                     1
sector-5 sheetla colony                                        1
garauli kalan                                                  1
v block dlf phase 3                                            1
sector-5 sohna                                                 1
g block dlf city phase 1                                       1
saroop garden rajendra park                                    1
hsiidc plot sector 1 imt manesar                               1
rattan garden                                                  1
bhimgarh kheri phase 3                                         1
hno 13 sagar enclave sura                                      1
bptp                                                           1
om nagar                                                       1
near khandsa road                                              1
part 3 sector 5                                                1
naharpur rupa                                                  1
jat colony,fazilpur/taj nagar road                             1
lucknow                                                        1
heritage city                                                  1
khandsa                                                        1
Name: sector, dtype: int64

In [13]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [14]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [15]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [16]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [17]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [18]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [19]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [20]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [21]:
df['sector'].value_counts()

sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 90                      90
sector 81                      90
sector 65                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      68
sector 50                      65
sector 107                     60
sector 108                     59
sector 48                      58
sector 2                       57
sector 95                      57
sector 56                      57
sector 89                      56
sector 70a                     55
sector 43                      53
sector 37c                     53
sector 70                      53
sector 84                      51
sector 26                      51
sector-33 sohna road           51
sector 49                      49
sector 67                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 25                      43
sector 113                     43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 12                      30
sector 68                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 112                     25
sector 24                      24
sector 57                      24
sector 105                     23
sector 14                      23
sector 88a                     23
sector 33                      23
sector 111                     22
sector 67a                     22
sector 11                      21
sector 3                       20
sector 82a                     20
sector 22                      20
sector 78                      19
sector 47                      19
sector 91                      18
gwal pahari                    18
sector 63a                     18
sector 74                      18
sector 62                      17
sector 99                      16
sector 110                     16
sector 60                      15
sector 63                      15
sector 55                      15
sector 52                      14
sector 1 manesar               14
sector 76                      14
sector 53                      14
sector 36a                     13
sector 6                       13
sector 4 phase 2               13
sector 46                      13
sector 9                       13
sohna road road                12
sector 31                      12
sector 93                      12
sector 38                      12
sector 39                      12
sector 9a                      11
sector 41                      11
sector 3 phase 3 extension     11
sector 13                      10
sector 1a manesar              10
sector 45                      10
manesar                         9
sector 95a                      9
sector 3 phase 2                9
c block sector 43               9
dwarka expressway               8
sector 23                       8
sector 8                        8
sector 17                       8
sector 2 extension              8
sector 10a                      8
sector 89 a                     8
sector 40                       8
sector 59                       8
sector 51                       7
sector 58                       7
sector 36 sohna road            7
sector 5                        6
sector 21                       6
sector 1                        6
new sector 2                    5
sector 23a                      5
sector 30                       5
sector 80                       5
new                             4
sector 36                       4
sector 3a                       4
sector 12a                      4
sector 27                       3
sector 17a                      3
b block sector 43               3
sector 73                       3
sector 110 a                    3
maruti kunj                     3
patel nagar                     3
sector 88b                      3
sector 15                       3
a block sector 43               3
sector 17b                      3
Name: sector, dtype: int64

In [22]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [23]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [24]:
df[df['sector'] == 'new']

,property_name,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type
1452,4 BHK Flat in New Gurgaon,sare homes,0.85,new,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN,NaN
3185,2 BHK Flat in New Gurgaon,takshila heights sector 37 c,0.67,new,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN,NaN
3467,2 BHK Flat in New Gurgaon,green court,0.38,new,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN,NaN
3587,4 BHK Flat in New Gurgaon,dlf 76,4.00,new,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN,NaN

In [25]:
df.loc[955,'sector'] = 'sector 37'
df.loc[2800,'sector'] = 'sector 92'
df.loc[2838,'sector'] = 'sector 90'
df.loc[2857,'sector'] = 'sector 76'

In [26]:
df[df['sector'] == 'new sector 2']

,property_name,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type
74,2 Bedroom House for sale in New Palam Vihar,my home,0.34,new sector 2,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5...",house
628,3 Bedroom House for sale in New Palam Vihar,independent,1.00,new sector 2,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",house
965,2 BHK Flat in New Palam Vihar,ompee k s residency,1.60,new sector 2,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ...",NaN
1761,2 BHK Flat in New Palam Vihar,my home,0.28,new sector 2,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ...",NaN
2119,2 BHK Flat in New Palam Vihar,my home,0.22,new sector 2,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E...",NaN

In [27]:
df.loc[[311,1072,1486,3040,3875],'sector'] = 'sector 110'

In [28]:
df.shape

(3816, 21)

In [33]:
df.duplicated().sum()

13

In [34]:
df_no_duplicates = df.drop_duplicates()

In [35]:
df.head()

,property_name,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type
0,4 BHK Flat in Mehrauli Gurgaon Road,essel towers,2.75,sector 14,12500.0,2200.0,Built Up area: 2200 (204.39 sq.m.),4,5,3+,"study room,servant room","Mehrauli Gurgaon Road, Mehrauli Gurgaon Road, ...",8.0,East,10+ Year Old,"['Mg road metro station', 'Iffco chowk metro s...","Recently renovated, tastefully done 4 bed room...","['1 Water Purifier', '9 Fan', '1 Exhaust Fan',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5...",NaN
1,2 BHK Flat in Sector 95A Gurgaon,signature signum 95a,0.40,sector 95,7782.0,514.0,Carpet area: 514 (47.75 sq.m.),2,2,2,not available,"Sector 95A Gurgaon, Gurgaon, Haryana",3.0,East,0 to 1 Year Old,NaN,Prime location\r\nAll necessary shops are in p...,"['3 Fan', '1 Geyser', '5 Light', '1 Chimney', ...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment5 out of 5', 'Safety5 out of 5', ...",NaN
2,3 BHK Flat in Sector 37D Gurgaon,bptp terra,1.71,sector 37d,7804.0,2191.0,Built Up area: 2191 (203.55 sq.m.),3,3,3+,study room,"7th Floor, Sector 37D Gurgaon, Gurgaon, Haryana",7.0,South-West,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",This beautiful 3 bhk flat in sector 37d gurgao...,"['6 Fan', '5 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Swimming Pool', 'Park', 'Internet...","['Green Area4.5 out of 5', 'Construction4.5 ou...",NaN
3,3 BHK Flat in Sector 37D Gurgaon,bptp terra,1.72,sector 37d,7850.0,2191.0,Super Built up area 2191(203.55 sq.m.),3,3,3+,servant room,"9th Floor, Sector 37D Gurgaon, Gurgaon, Haryana",10.0,South-East,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",Check out this 3 bhk apartment for sale in bpt...,"['5 Fan', '5 Light', '3 AC', 'No Bed', 'No Chi...","['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...","['Green Area4.5 out of 5', 'Construction4.5 ou...",NaN
4,3 BHK Flat in Sector 63 Gurgaon,dhoot time residency,3.00,sector 63,18271.0,1642.0,Built Up area: 1642 (152.55 sq.m.)Carpet area:...,3,3,3+,servant room,"Sector 63, Sector 63 Gurgaon, Gurgaon, Haryana",14.0,NaN,1 to 5 Year Old,"['Metro Station', 'High end group housing', 'N...",Best in class property available at sector 63 ...,"['3 Wardrobe', '8 Fan', '1 Exhaust Fan', '3 Ge...",NaN,"['Green Area4 out of 5', 'Construction4 out of...",NaN

In [37]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)